import requests

chat_id='@testing1151' #telegram channel name
BOT_API_KEY="5376762930:AAEr09cQy9qVMuqkjEDPn72Sdb40MqIh6y0" #the API Key generated by BotFather when creating bot

def send_message(message):
    try:
        request_text='https://api.telegram.org/bot'+BOT_API_KEY+'/sendMessage?chat_id='+chat_id+'&text='+message
        response = requests.get(request_text)
        if(response.json()['ok']):
            print("message sent successfully")
        elif(response.json()['ok']==False):
            print("Error occured: ",response.json())

    except Exception as error:
        print("Error occured: ",error)

def send_Photo(file,caption):
    try:
        if(caption):
            request_text='https://api.telegram.org/bot'+BOT_API_KEY+'/sendPhoto?chat_id='+chat_id+"&caption="+caption
        else:
            request_text = 'https://api.telegram.org/bot' + BOT_API_KEY + '/sendPhoto?chat_id=' + chat_id
        response = requests.post(request_text,files=file)
        if(response.json()['ok']):
            print("message sent successfully")
        elif(response.json()['ok']==False):
            print("Error occured: ",response.json())

    except Exception as error:
        print("Error occured: ",error)



def send_Document(file,caption):
    try:
        if caption:
            request_text='https://api.telegram.org/bot'+BOT_API_KEY+'/sendDocument?chat_id='+chat_id+"&caption="+caption
        else:
            request_text = 'https://api.telegram.org/bot' + BOT_API_KEY + '/sendDocument?chat_id=' + chat_id
        response = requests.post(request_text,files=file)
        if(response.json()['ok']):
            print("message sent successfully")
        elif(response.json()['ok']==False):
            print("Error occured: ",response.json())

    except Exception as error:
        print("Error occured: ",error)



#sending message
send_message("testing")

#for sending photo
files={'photo':open("male.jpg",'rb')}
caption="photo"
send_Photo(files,caption)

#for sending document
files={'document':open("test.txt",'rb')}
caption="text document"
send_Document(files,caption)
